name: auto-assign-issue

on:
  issues:
    types:
      - opened

jobs:
  call-reusable-workflow:
    uses: oedokumaci/oedokumaci/.github/workflows/auto-assign-issue.yml@main
    with:
      assignees: "oedokumaci"
      numOfAssignee: 1
