name: quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:
  call-quality-job:
    uses: oedokumaci/oedokumaci/.github/workflows/quality.yml@main
    with:
      os_version: "ubuntu-latest"
      python_version: "3.13"
