name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8
  PYTHONIOENCODING: UTF-8

jobs:
  call-test-job:
    strategy:
      matrix:
        os_version:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python_version:
          - "3.13"
    uses: oedokumaci/oedokumaci/.github/workflows/tests.yml@main
    with:
      os_version: ${{ matrix.os_version }}
      python_version: ${{ matrix.python_version }}
